### ISSUE TITLE
Running after a fresh checkout gives error "Graph is broken"

### ISSUE THREAD

**Issue by ahungry** [mkrauss/ticc#4]
This happens after checking out the project and running against a ticc.json as such:

``` php
{
    "database": {
        "name": "ticc"
    }
}

```

where 'ticc' is a newly created database

**Comment by mkrauss** [comment]
This message relates to having basically no error detection in the topological sort. It just knows that it has no sortable elements, but can't tell if it is because of a cycle in the graph (which Ticc should report as a circular dependency); or a vector that points to an element not on the graph (which Ticc should report as a bad dependency). However, I am not sure off hand why it would happen with no changes available, since that should become an empty graph, which should just fall through the while loop and return an empty "sorted" array... Will have to look in to that.

**Comment by mkrauss** [comment]
OK I tried, can't reproduce. If I am in the test-plan directory, it successfully deploys. If I'm in an empty directory (except for the ticc.json file) it says:

> Deploying: ... Nothing to deploy.

Am I missing something to reproduce this?

**Comment by ahungry** [comment]
It had to do with the running it from the project's top level with no setting in the json for the path plan_directory, and with no command specified, but in the latest head it isn't an issue anymore, so I'll go ahead and close this issue.
